### ISSUE TITLE
Missing @throws tag for __soapCall

### ISSUE THREAD

**Issue by Flexo013** [phpstan/php-8-stubs#47]
The `__soapCall` function can throw a `SoapFault` Exception.

From the [documentation](https://www.php.net/manual/en/soapclient.soapcall.php):

> On error, a call to a SOAP function can cause PHP to throw exceptions or return a [SoapFault](https://www.php.net/manual/en/class.soapfault.php) object if exceptions are disabled.

An example of catching a thrown `SoapFault` can be found in the examples of the `is_soap_fault` [documentation](https://www.php.net/manual/en/function.is-soap-fault).

[Relevant code in PHPStan stubs.](https://github.com/phpstan/php-8-stubs/blob/main/stubs/ext/soap/SoapClient.php#L21)
[Related PR for fixing the stubs in JetBrains stubs.](https://github.com/JetBrains/phpstorm-stubs/pull/1516)

This results in PHPStan wrongly reporting `Dead catch - Exception is never thrown in the try block` issues.

---
I'm not sure if this is the correct location to report this issue, but I couldn't find a better location to do so.

**Comment by ondrejmirtes** [comment]
> I'm not sure if this is the correct location

It's not. PHPStan 1.9.x-dev and 1.10.x-dev should contain your fix after this update (https://github.com/phpstan/phpstan-src/pull/2185) so please test it and see if it no longer reports your false positive. If it still does, open a bug report in phpstan/phpstan. Thanks.
