### ISSUE TITLE
Exclude zend_test and dl_test

### ISSUE THREAD

**Issue by JanTvrdik** [phpstan/php-8-stubs#53]
Extensions `zend_test` and `dl_test` are internal to PHP and should be excluded from stubs.

**Comment by ondrejmirtes** [comment]
Fixed: https://github.com/phpstan/php-8-stubs/commit/baf8188ea45cf528de62211c5b5efd5675b114d2 + https://github.com/phpstan/php-8-stubs/commit/945d7554e8bc083afb3d13ae4431017aaf786f52
